### PR TITLE
AQ32: Move v2 related files into v2 folder; add pin mapping for v1

### PR DESCRIPTION
**Pull request by yamahabest**
And renamed "GND" to "Ground", and "NC" to "Not Connected" on the original v2 overview.

### CODE REVIEW

**Comment by yamahabest** [comment]
@jihlein A quick inspection on the V1 board would be very appreciated!

**Comment by tracernz** [comment]
Might be a good idea to tag this with AQ32: prefix so it's easier to track commit history after merge.

**Comment by mlyle** [comment]
@tracernz --- I changed the title-- when I squash-and-merge it will be used as the title for the main commit / fix this up.

**Comment by tracernz** [comment]
@mlyle

**Pull request merged**
